### PR TITLE
Yworks sponsoring

### PR DESCRIPTION
**Pull request by matthiasbeyer**
yworks is sponsoring, they asked to be included in the website.

@primeos please have a look.

### CODE REVIEW

**Comment by primeos** [comment]
Can we also use this logo from their website (more suitable aspect ratio)?: https://www.yworks.com/assets/images/logos/yWorks-H-Orange.3f964ff412.svg

Otherwise the logo will be way larger than the other logos (which probably looks especially bad if we add more logos to that row) since only the width is limited:
image

**Comment by matthiasbeyer** [comment]
The logo in the PR is the one that yworks has send to me for inclusion.

**Comment by primeos** [comment]
> The logo in the PR is the one that yworks has send to me for inclusion.

Well, I guessed that much... :D Doesn't mean that the other one isn't fine as well though.

But together with the ifm logo it looks good enough for now (I just asked a few other orga members):
image

**Comment by primeos** [comment]
GitHub somehow doesn't update the PR after my force-push / rebase:
image

Very weird...

**Comment by primeos** [comment]
image

Such crappy software... :o
I thought closing + reopening might fix things but looks like I'll have to create a new PR...

**Comment by matthiasbeyer** [comment]
From what I see this is a layer 8 problem. 😂

**Comment by primeos** [comment]
Nope, but I'm curious: Where do you see the layer 8 problem?

**Comment by matthiasbeyer** [comment]
Ah you mean your force-pushed _this_ branch and it didn't update?
I misunderstood that. Well then it is a github issue.

**Comment by primeos** [comment]
Yes, exactly :)
I'm not sure if I ever ran into this bug before (when it happened it was completely new to me but in hindsight I have a bit of a déjà vu feeling).
Apparently this isn't a new issue: https://github.com/orgs/community/discussions/16351
It's very strange though that I hit this bug with https://github.com/tuebix/tuebixorg/pull/19 again - but at least a second force-push after an amend to update the commit date did finally fully update the PR.
And it wasn't a caching issue as I tested it via the incognito mode and via my smartphone as well.
The fact that it shows the force-push event but doesn't update the diffs, commits, and conflicts is especially weird...
Anyway, I guess it's just one of the many rare GitHub glitches.

**Pull request closed without merging**
